import historyImg from "./history.png";

const AnimeHistory = () => {
    return (
        <div className="mt-16 py-3 px-4">
            <p className="tracking-wider text-xl text-white italic">Let's Learn about Anime History</p>
            <hr className="mt-2" />
            <p className="text-[yellow] tracking-wider mt-4 text-2xl">What Is Anime?</p>
            <img src={historyImg} className="w-[50%] md:w-[20%] mx-auto" />
            <p className="text-white tracking-wider mt-1 text-justify">The history of anime can be traced back to the start of the 20th century, with the earliest verifiable films dating from 1907.Before the advent of film, Japan already had a rich tradition of entertainment with colourful painted figures moving across the projection screen in utsushi-e (写し絵), a particular Japanese type of magic lantern show popular in the 19th century. Possibly inspired by European phantasmagoria shows, utsushi-e showmen used mechanical slides and developed lightweight wooden projectors (furo) that were handheld so that several performers could each control the motions of different projected figures.</p>
            <br />
            <p className="text-white tracking-wider text-justify">The second generation of animators in the late 1910s included Ōten Shimokawa, Jun'ichi Kōuchi and Seitaro Kitayama, commonly referred to as the "fathers" of anime. Propaganda films, such as Momotarō no Umiwashi (1943) and Momotarō: Umi no Shinpei (1945), the latter being the first anime feature film, were made during World War II. During the 1970s, anime developed further, with the inspiration of Disney animators, separating itself from its Western roots, and developing distinct genres such as mecha and its super robot subgenre. Typical shows from this period include Astro Boy, Lupin III and Mazinger Z. During this period several filmmakers became famous, especially Hayao Miyazaki and Mamoru Oshii.</p>

            <p className="text-[yellow] tracking-wider mt-4 text-2xl">Origins of anime (early 1900s – 1922)</p>
            <p className="text-white tracking-wider my-2 text-justify leading-relaxed">
                According to Natsuki Matsumoto, the first animated film produced in Japan may have stemmed from as early as 1907. Known as Katsudō Shashin (活動写真, "Activity Photo"), from its depiction of a boy in a sailor suit drawing the characters for katsudō shashin, the film was first found in 2005. It consists of fifty frames stencilled directly onto a strip of celluloid. This claim has not been verified though and predates the first known showing of animated films in Japan. The date and first film publicly displayed is another source of contention: while no Japanese-produced animation is definitively known to date before 1916, the possibility exists that other films entered Japan and that no known records have surfaced to prove a showing prior to 1912. Film titles have surfaced over the years, but none have been proven to predate this year. The first foreign animation is known to have been found in Japan in 1910, but it is not clear if the film was ever shown in a cinema or publicly displayed at all. Yasushi Watanabe found a film known as Fushigi no Bōrudo (不思議のボールド, "Miracle Board") in the records of the Yoshizawa Shōten (吉沢商店) company. The description matches James Blackton's Humorous Phases of Funny Faces, though academic consensus on whether or not this is a true animated film is disputed. According to Kyokko Yoshiyama, the first animated film called Nippāru no Henkei (ニッパールの変形, "Nippāru's Transformation") was shown in Japan at the Asakusa Teikokukan (浅草帝国館) in Tokyo sometime in 1912. However, Yoshiyama did not refer to the film as "animation.” The first confirmed animated film shown in Japan was Les Exploits de Feu Follet by Émile Cohl on May 15, 1912. While speculation and other "trick films" have been found in Japan, it is the first recorded account of a public showing of a two-dimensional animated film in Japanese cinema. During this time, German animations marketed for home release were distributed in Japan. In 1914, U.S. and European cartoons were introduced to Japan, inspiring Japanese creators like Junichi Kouchi and Seitaro Kitayama, both of whom were considered the "fathers of anime."
            </p>
            <p className="text-[yellow] text-2xl mt-4">1960s</p>
            <hr className="mt-2" />
            <p className="text-[white] tracking-wider text-justify my-2 leading-relaxed">In the 1960s, the unique style of Japanese anime began forming, with large eyed, big mouthed, and large headed characters. The first anime film to be broadcast was Moving pictures in 1960. 1961 saw the premiere of Japan's first animated television series, Instant History, although it did not consist entirely of animation. Magic Boy, known in Japan as Shōnen Sarutobi Sasuke (少年猿飛佐助, "The Boy Sarutobi Sasuke"), is a 1959 Japanese animated feature film released on December 25, 1959. Released as Toei Animation's second theatrical anime, the film was released in theaters in United States by Metro-Goldwyn-Mayer on June 22, 1961, making it the first anime film to be released in the country, followed by The Tale of the White Serpent on July 8, 1961. These films were popular enough they paved the way for other anime to follow. Astro Boy, created by Osamu Tezuka, premiered on Fuji TV on January 1, 1963. It became the first anime series shown widely to Western audiences, especially to those in the United States, becoming relatively popular and influencing U.S. popular culture, with American companies acquiring various titles from Japanese producers. Astro Boy was highly influential to other anime in the 1960s, and was followed by a large number of anime about robots or space. While Tezuka released many other animated shows, like Jungle Emperor Leo, anime took off, studios saw it as a commercial success, even though no new programs from Japan were shown on major U.S. broadcast media from the later 1960s to late 1970s. The 1960s also brought anime to television and in America.</p>

            <p className="text-[yellow] text-2xl mt-4">1970s</p>
            <hr className="mt-2" />
            <p className="text-[white] tracking-wider text-justify my-2 leading-relaxed">During the 1970s, the Japanese film market shrank due to competition from television. This reduced Toei animation's staff and many animators went to studios such as A Pro and Telecom animation. Mushi Production went bankrupt (though the studio was revived 4 years later), its former employees founding studios such as Madhouse and Sunrise. Many young animators were thrust into the position of director, and the injection of young talent allowed for a wide variety of experimentation. One of the earliest successful television productions in the early 1970s was Tomorrow's Joe (1970), a boxing anime which has become iconic in Japan. 1971 saw the first installment of the Lupin III anime. Contrary to the franchise's current popularity, the first series ran for 23 episodes before being cancelled. The second series (starting in 1977) saw considerably more success, spanning 155 episodes over three years.</p>

            <p className="text-[yellow] text-2xl mt-4">1980s</p>
            <hr className="mt-2" />
            <p className="text-[white] tracking-wider text-justify my-2 leading-relaxed">In the 1980s, anime started to go through a "visual quality renewal" thanks to new directors like Hayao Miyazaki and Isao Takahata, who founded Studio Ghibli in 1985, and Katsuhiro Ōtomo. Anime began to deal with more nuanced and complex stories, while Boy's Love continued to impact cultural norms, taking root across East Asia, as countries such as South Korea, Thailand, and China ingested these Japanese pop culture exports. The shift towards space operas became more pronounced with the commercial success of Star Wars (1977). This allowed for the space opera Space Battleship Yamato (1974) to be revived as a theatrical film. Mobile Suit Gundam (1979) was also successful and revived as a theatrical film in 1982. The success of the theatrical versions of Yamato and Gundam is seen as the beginning of the anime boom of the 1980s, and of "Japanese Cinema's Second Golden Age".</p>

            <p className="text-[yellow] text-2xl mt-4">1990s</p>
            <hr className="mt-2" />
            <p className="text-[white] tracking-wider text-justify my-2 leading-relaxed">
                In 1995, Hideaki Anno wrote and directed the controversial anime Neon Genesis Evangelion. This show became popular in Japan among anime fans and became known to the general public through mainstream media attention. It is believed that Anno originally wanted the show to be the ultimate otaku anime, designed to revive the declining anime industry, but midway through production he also made it into a heavy critique of the subculture. It culminated in the successful but controversial film The End of Evangelion which grossed over $10 million in 1997. The many violent and sexual scenes in Evangelion caused TV Tokyo to increase censorship of anime content. As a result, when Cowboy Bebop was first broadcast in 1998, it was shown heavily edited and only half the episodes were aired; it too gained heavy popularity both in and outside of Japan.
            </p>

            <p className="text-[yellow] text-2xl mt-4">2000</p>
            <hr className="mt-2" />
            <p className="text-[white] tracking-wider text-justify my-2 leading-relaxed">
                The "Evangelion-era" trend continued into the 2000s with Evangelion-inspired mecha anime such as RahXephon (2002) and Zegapain (2006) – RahXephon was also intended to help revive 1970s-style mecha designs. The number of anime productions began to decline after peaking in 2006 due to alternative forms of entertainment, less ad revenue, and other reasons, with TV Tokyo remaining one of the only channels airing anime shows. Even so, anime began entering U.S. homes like never before, with fans able to get their hands on Japanese-language originals of anime they watched, thanks to the internet.

                The real robot genre (including the Gundam and Macross franchises), which had declined during the 1990s, was revived in the early 2000s with the success of shows such as FLCL (2000), Mobile Suit Gundam SEED (2002), Eureka Seven (2005), Code Geass: Lelouch of the Rebellion (2006), Mobile Suit Gundam 00 (2007), and Macross Frontier (2008).
            </p>

            <p className="text-[yellow] text-2xl mt-4">2010</p>
            <hr className="mt-2" />
            <p className="text-[white] tracking-wider text-justify my-2 leading-relaxed">
                In May 2012, the Toonami programming block in the United States was relaunched as a late night adult-oriented action block on Adult Swim, bringing more uncut popular anime back to a wider audience on cable television. In addition to broadcasting or re-broadcasting previously released dubbed anime, the block (as well as Adult Swim itself) has overseen the worldwide premiere of English dubbed releases for various anime, including but not limited to: Durarara!! (2010), Deadman Wonderland (2011), Hunter x Hunter (2011), Sword Art Online (2012), JoJo's Bizarre Adventure (2012), Attack on Titan (2013), Kill la Kill (2013), Space Dandy (2014), Akame ga Kill! (2014), Parasyte -the maxim- (2014), One-Punch Man (2015), Dragon Ball Super (2015), My Hero Academia (2016), Boruto: Naruto Next Generations (2017), and Demon Slayer: Kimetsu no Yaiba (2019).
            </p>

            <p className="text-[yellow] text-2xl mt-4">2020</p>
            <hr className="mt-2" />
            <p className="text-[white] tracking-wider text-justify my-2 leading-relaxed">
                The international popularity and demand of anime rose highly during the COVID-19 pandemic due to the medium's increased availability on streaming services.

                Demon Slayer: Kimetsu no Yaiba the Movie: Mugen Train became the highest-grossing Japanese film and the world's highest-grossing films of 2020. It also became the fastest grossing film in Japanese cinema, because in 10 days it made 10 billion yen ($95.3m; £72m). It beat the previous record of Spirited Away which took 25 days.

                In 2021, the anime adaptations of Jujutsu Kaisen, Demon Slayer: Kimetsu no Yaiba and Tokyo Revengers were among the top 10 most discussed TV shows worldwide on Twitter.

                In 2022, Attack on Titan won the award of "Most In-Demand TV Series in the World 2021" in the Global TV Demand Awards. Attack on Titan became the first ever non-English language series to earn the title of World’s Most In-Demand TV Show, previously held by only The Walking Dead and Game of Thrones.
            </p>
        </div>
    )
}

export default AnimeHistory